#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RUNNER="$ROOT/src/sst/elements/golem/tests/small/muticore_attention/run_fused_attention_scale.sh"

export GOLEM_ATTENTION_REUSE_WINDOW_QK_BRIDGE=1
export GOLEM_ATTENTION_WORKER_CLUSTER_BRIDGE=1
export GOLEM_ATTENTION_QK_INPUT_PIPELINE=1
export GOLEM_ATTENTION_KV_BUFFER_COUNT=2
export GOLEM_NOC_LINK_BW="${GOLEM_NOC_LINK_BW:-512GB/s}"
export GOLEM_NOC_XBAR_BW="${GOLEM_NOC_XBAR_BW:-1024GB/s}"
export GOLEM_GM_LINK_BW="${GOLEM_GM_LINK_BW:-256GB/s}"
export GOLEM_DIRCTRL_HIGHLINK_BW="${GOLEM_DIRCTRL_HIGHLINK_BW:-512GB/s}"
export GOLEM_NOC_INPUT_BUF_SIZE="${GOLEM_NOC_INPUT_BUF_SIZE:-128KB}"
export GOLEM_NOC_OUTPUT_BUF_SIZE="${GOLEM_NOC_OUTPUT_BUF_SIZE:-128KB}"
export GOLEM_GM_BUFFER_LENGTH="${GOLEM_GM_BUFFER_LENGTH:-128KB}"
export GOLEM_LOCAL_GM_BYTES_PER_CYCLE="${GOLEM_LOCAL_GM_BYTES_PER_CYCLE:-256}"

exec "$RUNNER" "$@"
