#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RUNNER="$ROOT/src/sst/elements/golem/tests/small/muticore_attention/run_fused_attention_scale.sh"

export GOLEM_ATTENTION_REUSE_WINDOW_QK_BRIDGE=1
export GOLEM_ATTENTION_WORKER_CLUSTER_BRIDGE=1
export GOLEM_ATTENTION_WORKER_CLUSTER_QK_WORKERS_PER_MANAGER=2
export GOLEM_ATTENTION_WORKER_CLUSTER_ROW_PRIORITY="${GOLEM_ATTENTION_WORKER_CLUSTER_ROW_PRIORITY:-1}"
export GOLEM_ATTENTION_WORKER_CLUSTER_V_BROADCAST="${GOLEM_ATTENTION_WORKER_CLUSTER_V_BROADCAST:-1}"
export GOLEM_ATTENTION_WORKER_CLUSTER_DYNAMIC_PV="${GOLEM_ATTENTION_WORKER_CLUSTER_DYNAMIC_PV:-0}"
export GOLEM_ATTENTION_QK_INPUT_PIPELINE=1
export GOLEM_ATTENTION_KV_BUFFER_COUNT=2
export GOLEM_ATTENTION_PV_PANEL_PREFETCH="${GOLEM_ATTENTION_PV_PANEL_PREFETCH:-1}"
export GOLEM_DMA_WINDOW_K_TILES="${GOLEM_DMA_WINDOW_K_TILES:-4}"

# Keep the fabric and SRAM parameters identical to the 4:12 baseline.
export GOLEM_NOC_LINK_BW="${GOLEM_NOC_LINK_BW:-512GB/s}"
export GOLEM_NOC_XBAR_BW="${GOLEM_NOC_XBAR_BW:-1024GB/s}"
export GOLEM_GM_LINK_BW="${GOLEM_GM_LINK_BW:-256GB/s}"
export GOLEM_DIRCTRL_HIGHLINK_BW="${GOLEM_DIRCTRL_HIGHLINK_BW:-512GB/s}"
export GOLEM_NOC_INPUT_BUF_SIZE="${GOLEM_NOC_INPUT_BUF_SIZE:-128KB}"
export GOLEM_NOC_OUTPUT_BUF_SIZE="${GOLEM_NOC_OUTPUT_BUF_SIZE:-128KB}"
export GOLEM_GM_BUFFER_LENGTH="${GOLEM_GM_BUFFER_LENGTH:-128KB}"
export GOLEM_LOCAL_GM_BYTES_PER_CYCLE="${GOLEM_LOCAL_GM_BYTES_PER_CYCLE:-256}"

# Eight QK producers share each manager request path. Keep the WCP's physical
# 24-slot reuse geometry unchanged and widen the software request window. A
# larger NIC credit cap is deliberately not the default: it lets speculative V
# prefetches contend with demand traffic and regresses this workload.
export GOLEM_REQUEST_SCHEDULER_QUEUE_DEPTH="${GOLEM_REQUEST_SCHEDULER_QUEUE_DEPTH:-2048}"
export GOLEM_DMA_NODE_CHUNK_CREDITS="${GOLEM_DMA_NODE_CHUNK_CREDITS:-128}"
export GOLEM_SCHED_ISSUE_BUDGET_PER_TICK="${GOLEM_SCHED_ISSUE_BUDGET_PER_TICK:-2}"
export GOLEM_SCHED_SUBMIT_BATCH_SIZE="${GOLEM_SCHED_SUBMIT_BATCH_SIZE:-4}"
export GOLEM_SCHED_DONE_BATCH_SIZE="${GOLEM_SCHED_DONE_BATCH_SIZE:-4}"
export GOLEM_DMA_GROUP_RR_ENABLE="${GOLEM_DMA_GROUP_RR_ENABLE:-0}"
export GOLEM_DMA_TILE_CHUNK_QUANTUM="${GOLEM_DMA_TILE_CHUNK_QUANTUM:-1}"

exec "$RUNNER" "$@"
