// Copyright 2009-2025 NTESS. Under the terms
// of Contract DE-NA0003525 with NTESS, the U.S.
// Government retains certain rights in this software.
//
// Copyright (c) 2009-2025, NTESS
// All rights reserved.
//
// Portions are copyright of other developers:
// See the file CONTRIBUTORS.TXT in the top level directory
// of the distribution for more information.
//
// This file is part of the SST software package. For license
// information, see the LICENSE file in the top level directory of the
// distribution.

#ifndef _H_ANALOG_ROCC_INT
#define _H_ANALOG_ROCC_INT

#include <sst/elements/golem/rocc/roccAnalog.h>

namespace SST {
namespace Golem {

class RoCCAnalogInt : public RoCCAnalog<int64_t> {
public:
    SST_ELI_REGISTER_SUBCOMPONENT(
        RoCCAnalogInt,
        "golem",
        "RoCCAnalogInt",
        SST_ELI_ELEMENT_VERSION(1, 0, 0),
        "Implements a RoCC accelerator interface for the analog core (int version)",
        SST::Golem::RoCCAnalog<int64_t>
    )

    SST_ELI_DOCUMENT_SUBCOMPONENT_SLOTS(
        {"memory_interface", "Set the interface to memory", "SST::Interfaces::StandardMem"},
        {"array", "Analog array model", "SST::Golem::ComputeArray"},
        {"global_memory", "Local global memory","SST::Golem::GlobalMemoryAPI"},
        {"group_ctrl", "Group control endpoint", "SST::SubComponent"},
        {"request_scheduler", "Request scheduler endpoint", "SST::SubComponent"})

    SST_ELI_DOCUMENT_PORTS(
        {"dcache_link", "Connects the RoCC frontend to the data cache", {}})

    SST_ELI_DOCUMENT_PARAMS(
        {"verbose", "Set the verbosity of output for the RoCC", "0"},
        {"max_instructions",
         "Set the maximum number of RoCC instructions permitted in the queue", "8"},
        {"clock",
         "Clock frequency for component TimeConverter. MMIOTile is Unclocked but "
         "subcomponents use the TimeConverter", "1GHz"},
        {"mmioAddr", "Address MMIO interface"},
        {"numArrays", "Number of distinct arrays in the tile.", "1"},
        {"arrayInputSize", "Length of input vector (implies array rows)."},
        {"arrayOutputSize", "Length of output vector (implies array columns)."},
        {"inputOperandSize", "Size of input operand in bytes."},
        {"outputOperandSize", "Size of output operand in bytes."},
        {"attention_window_offset", "Offset of the fused Attention Local GM window", "0xC0000"},
        {"attention_window_bytes", "Capacity of the fused Attention Local GM window", "0x10000"},
        {"attention_kv_tile_rotation", "Rotate the first streamed K/V tile across HBM bands", "0"},
        {"attention_kv_double_buffer", "Prefetch streamed K/V tiles into alternating Local GM buffers", "0"},
        {"attention_kv_buffer_count", "Number of Local GM K/V staging buffers (1..3)", "2"},
        {"attention_kv_distribution_enable", "Load each K/V tile once per four-worker manager group and distribute it", "0"},
        {"attention_key_block_rows", "Attention cluster K/V tile rows (32 or 64)", "32"},
        {"attention_kv_second_lookahead", "Issue N+2 K/V prefetch after both current operands are released", "1"},
        {"attention_kv_cross_query_prefetch", "Prefetch the next query block's first K/V tile into released double-buffer storage", "0"},
        {"attention_kv_pair_reuse", "Reuse each streamed K/V tile across a bounded group of adjacent non-causal query blocks", "0"},
        {"attention_kv_query_group_size", "Adjacent query blocks sharing each streamed K/V tile: 2 or 4", "2"},
        {"attention_pv_v_tile_reuse", "Read each PV V tile from Local GM once and reuse it across panels", "0"},
        {"attention_pv_v_tile_group_retention", "Retain the bounded PV V staging tile across members of one physical query group", "0"},
        {"attention_pv_v_tile_buffer_bytes", "Capacity of the modeled PV V tile buffer in bytes", "16384"},
        {"attention_pv_v_tile_buffer_hit_ticks", "Latency in cycles for a PV V tile buffer hit", "1"},
        {"attention_pv_v_tile_buffer_bytes_per_cycle", "PV V tile buffer read bandwidth in bytes per cycle", "64"},
        {"attention_pv_v_tile_buffer_offset", "Offset of the PV V tile buffer within the Attention Local GM window", "0"},
        {"attention_pv_input_pipeline", "Pipeline Local GM P reads with Array input programming", "0"},
        {"attention_pv_compact_input", "Program only active PV input lanes and retain inactive lanes", "0"},
        {"attention_pv_input_residency", "Retain each key tile's P inputs across PV dimension panels", "0"},
        {"attention_o_accumulator_cbuffer", "Retain intermediate FP32 Attention O in WCP C-buffer", "0"},
        {"attention_pv_restore_pipeline", "Pipeline Local GM Oacc reads with Array output restore writes", "0"},
        {"attention_pv_output_pipeline", "Pipeline Array output reads with Local GM writes", "0"},
        {"attention_pv_o_row_fusion", "Fuse each 128-element PV output row into eight parallel O-accumulator banks", "0"},
        {"attention_pv_early_compute", "Start each PV Array when its input and output state are ready", "0"},
        {"attention_pv_matrix_softmax_overlap", "Program the first PV V matrix while Softmax runs", "0"},
        {"attention_pv_active_k", "Program and execute only the active PV key columns", "0"},
        {"attention_qk_early_compute", "Start each QK array as soon as its input programming completes", "0"},
        {"attention_qk_input_pipeline", "Overlap bounded QK K-row Local GM reads with Array input programming", "0"},
        {"attention_qk_readout_overlap", "Bound QK Array-output read-ahead while ordered Local GM writes retire", "0"},
        {"attention_qk_readout_window", "Maximum QK Array outputs issued ahead of ordered Local GM retirement", "2"},
        {"attention_qk_score_row_burst", "Transpose one QK score tile in the WCP C-buffer and write query-major 64B rows", "0"},
        {"attention_qk_panel_row_burst", "Deprecated alias for attention_qk_score_row_burst", "0"},
        {"attention_cross_tile_operand_pipeline", "Preload one grouped follower QK operand context during the current tile", "0"},
        {"attention_operand_context_banks", "Number of banked QK/PV operand contexts per physical array", "1"},
        {"attention_pv_matrix_broadcast", "Broadcast one PV matrix transfer to all query arrays", "0"},
        {"attention_generic_gemm_enable", "Route Attention QK/PV array operations through the shared GEMM engine", "0"},
        {"attention_milestone_trace", "Print parseable fused Attention lifecycle milestones", "0"},
        {"attention_tile_trace", "Print every fused Attention tile milestone in addition to final-tile milestones", "0"},
        {"progress_heartbeat", "Enable lightweight RoCC MVM progress heartbeat logs", "0"},
        {"progress_interval_cycles", "Progress heartbeat interval in RoCC cycles", "50000"},
        {"progress_total_mvm_ops", "Expected total MVM ops for this core", "0"})

    SST_ELI_DOCUMENT_STATISTICS(
        {"roccs_issued", "Count number of RoCC instructions that are issued", "operations", 1},
        {"cycles_mvm_set", "Cycles consumed by mvm.set instructions", "cycles", 1},
        {"cycles_mvm_l", "Cycles consumed by mvm.l instructions", "cycles", 1},
        {"cycles_mvm", "Cycles consumed by mvm compute instructions", "cycles", 1},
        {"cycles_mvm_s", "Cycles consumed by mvm.s instructions", "cycles", 1},
        {"cycles_mvm_mv", "Cycles consumed by mvm.mv instructions", "cycles", 1},
        {"cycles_mvm_ovec2gm", "Cycles consumed by mvm.ovec2gm instructions", "cycles", 1},
        {"cycles_mvm_gm2ivec", "Cycles consumed by mvm.gm2ivec instructions", "cycles", 1},
        {"cycles_mvm_gm2imat", "Cycles consumed by mvm.gm2imat instructions", "cycles", 1},
        {"cycles_remote_st", "Cycles consumed by remote_st instructions", "cycles", 1},
        {"cycles_remote_ld", "Cycles consumed by remote_ld instructions", "cycles", 1},
        {"tensor_manager_jobs_issued", "Tensor jobs accepted by the manager RoCC", "jobs", 1},
        {"tensor_manager_workers_mapped", "Physical worker cores mapped by manager jobs", "workers", 1},
        {"tensor_manager_rows_dispatched", "Tensor rows dispatched by the manager RoCC", "rows", 1},
        {"tensor_manager_rows_completed", "Tensor rows completed at the manager RoCC", "rows", 1},
        {"tensor_manager_jobs_completed", "Tensor jobs completed by the manager RoCC", "jobs", 1},
        {"tensor_manager_descriptor_accept_tick", "Simulation tick when a manager descriptor is accepted", "ticks", 1},
        {"tensor_manager_band_dispatch_tick", "Simulation tick for each manager worker-band dispatch", "ticks", 1},
        {"tensor_manager_completion_received_tick", "Simulation tick for each manager worker completion", "ticks", 1},
        {"tensor_manager_complete_tick", "Simulation tick when all manager workers complete", "ticks", 1},
        {"tensor_manager_wait_observed_tick", "Simulation tick when software observes manager completion", "ticks", 1},
        {"attention_manager_jobs_issued", "Fused Attention jobs issued by manager", "jobs", 1},
        {"attention_manager_jobs_completed", "Fused Attention jobs completed by manager", "jobs", 1},
        {"attention_manager_bands_completed", "Fused Attention bands completed locally", "bands", 1},
        {"attention_manager_band_completions_received", "Attention band completions received by the root manager", "bands", 1},
        {"attention_tensor_jobs_completed", "Fused Attention tensors completed after manager aggregation", "jobs", 1},
        {"attention_manager_descriptor_accept_tick", "Tick when an Attention manager job is accepted", "ticks", 1},
        {"attention_manager_dispatch_tick", "Tick when an Attention manager dispatches all workers", "ticks", 1},
        {"attention_manager_local_complete_tick", "Tick when an Attention manager completes its local band", "ticks", 1},
        {"attention_manager_band_completion_received_tick", "Tick for each Attention manager band received by root", "ticks", 1},
        {"attention_tensor_complete_tick", "Tick when root completes the Attention tensor", "ticks", 1},
        {"attention_manager_wait_observed_tick", "Tick when software observes Attention manager completion", "ticks", 1},
        {"attention_worker_dispatch_accept_tick", "Tick when an Attention worker accepts a dispatch", "ticks", 1},
        {"attention_worker_qk_tile_complete_tick", "Tick when an Attention worker completes a QK tile", "ticks", 1},
        {"attention_worker_softmax_tile_complete_tick", "Tick when an Attention worker completes a Softmax tile", "ticks", 1},
        {"attention_worker_pv_tile_complete_tick", "Tick when an Attention worker completes a PV tile", "ticks", 1},
        {"attention_worker_output_dma_ack_tick", "Tick when an Attention worker receives an output DMA acknowledgement", "ticks", 1},
        {"attention_worker_intertile_total_ticks", "Total ticks across completed inter-tile transitions", "ticks", 1},
        {"attention_worker_intertile_output_dma_ticks", "Inter-tile output DMA ticks", "ticks", 1},
        {"attention_worker_intertile_query_load_ticks", "Inter-tile query load ticks", "ticks", 1},
        {"attention_worker_intertile_kv_load_ticks", "Inter-tile K/V load ticks", "ticks", 1},
        {"attention_worker_intertile_q_local_read_ticks", "Inter-tile local Q read ticks", "ticks", 1},
        {"attention_worker_intertile_qk_matrix_program_ticks", "Inter-tile QK matrix programming ticks", "ticks", 1},
        {"attention_worker_intertile_qk_input_program_ticks", "Inter-tile QK input programming ticks", "ticks", 1},
        {"attention_worker_intertile_qk_compute_readout_ticks", "Inter-tile QK compute and readout ticks", "ticks", 1},
        {"attention_worker_tile_total_ticks", "Total ticks across completed Attention tiles", "ticks", 1},
        {"attention_worker_tile_kv_load_ticks", "Attention tile K/V load ticks", "ticks", 1},
        {"attention_worker_tile_q_local_read_ticks", "Attention tile local Q read ticks", "ticks", 1},
        {"attention_worker_tile_qk_matrix_program_ticks", "Attention tile QK matrix programming ticks", "ticks", 1},
        {"attention_worker_tile_qk_input_program_ticks", "Attention tile QK input programming ticks", "ticks", 1},
        {"attention_worker_tile_qk_compute_readout_ticks", "Attention tile QK compute and readout ticks", "ticks", 1},
        {"attention_worker_tile_softmax_ticks", "Attention tile Softmax ticks", "ticks", 1},
        {"attention_worker_tile_pv_matrix_program_ticks", "Attention tile PV matrix programming ticks", "ticks", 1},
        {"attention_worker_tile_pv_input_program_ticks", "Attention tile PV input programming ticks", "ticks", 1},
        {"attention_worker_tile_pv_restore_output_ticks", "Attention tile PV output restore ticks", "ticks", 1},
        {"attention_worker_tile_pv_compute_ticks", "Attention tile PV compute ticks", "ticks", 1},
        {"attention_worker_tile_pv_output_readwrite_ticks", "Attention tile PV output read/write ticks", "ticks", 1},
        {"attention_kv_prefetch_tiles", "K/V tiles launched through double-buffer prefetch", "tiles", 1},
        {"attention_kv_prefetch_hits", "K/V prefetched tiles ready when consumed", "tiles", 1},
        {"attention_kv_prefetch_waits", "K/V prefetched tiles that blocked their consumer", "tiles", 1},
        {"attention_kv_prefetch_dma_ticks", "Ticks from K/V prefetch issue until both DMA reads complete", "ticks", 1},
        {"attention_kv_prefetch_ready_lead_ticks", "Ticks a ready K/V prefetch leads its consumer", "ticks", 1},
        {"attention_kv_prefetch_wait_ticks", "Ticks a K/V prefetch consumer waits for DMA completion", "ticks", 1},
        {"attention_kv_k_release_ticks", "Ticks from tile start until the current K buffer is no longer needed", "ticks", 1},
        {"attention_kv_v_release_ticks", "Ticks from tile start until the current V buffer is no longer needed", "ticks", 1},
        {"attention_kv_next_ready_at_release_tiles", "Tiles whose next K/V prefetch is ready when current K/V storage is released", "tiles", 1},
        {"attention_kv_second_lookahead_candidates", "Tiles eligible to prefetch a second lookahead into released K/V storage", "tiles", 1},
        {"attention_kv_second_lookahead_prefetches", "Second-lookahead K/V tiles actually launched into released storage", "tiles", 1},
        {"attention_kv_second_lookahead_lead_ticks", "Ticks from second-lookahead eligibility until the current tile boundary", "ticks", 1},
        {"attention_kv_cross_query_prefetches", "K/V tile-0 prefetches issued across query-block boundaries", "prefetches", 1},
        {"attention_kv_cross_query_hits", "Cross-query K/V prefetches ready at the next query-block boundary", "hits", 1},
        {"attention_kv_cross_query_waits", "Cross-query K/V prefetches still pending at the next query-block boundary", "waits", 1},
        {"attention_kv_cross_query_wait_ticks", "Ticks spent waiting for a cross-query K/V prefetch", "ticks", 1},
        {"attention_kv_pair_reuse_tiles", "Grouped-query tiles served from a retained K/V buffer", "tiles", 1},
        {"attention_kv_pair_reuse_bytes", "K/V DMA bytes avoided by bounded grouped-query reuse", "bytes", 1},
        {"attention_pv_input_pipeline_rows", "PV input rows issued through the pipelined path", "rows", 1},
        {"attention_cluster_pv_wavefront_rows", "Cluster P rows launched into PV as soon as their input is programmed", "rows", 1},
        {"attention_cluster_qk_matrix_lookahead_launches", "Next physical-tile K matrices started in an inactive operand bank", "tiles", 1},
        {"attention_cluster_qk_matrix_lookahead_hits", "Preprogrammed K matrices promoted at a physical tile boundary", "tiles", 1},
        {"attention_cluster_pv_matrix_lookahead_launches", "Next physical-tile V matrices started in an inactive operand bank", "tiles", 1},
        {"attention_cluster_pv_matrix_lookahead_hits", "Preprogrammed V matrices promoted before PV", "tiles", 1},
        {"attention_pv_restore_pipeline_rows", "PV output restore rows issued through the pipelined path", "rows", 1},
        {"attention_pv_output_pipeline_rows", "PV output rows issued through the pipelined writeback path", "rows", 1},
        {"attention_pv_early_compute_arrays", "PV Array operations started from per-Array readiness", "operations", 1},
        {"attention_pv_matrix_overlap_tiles", "Attention tiles with first PV matrix programming overlapped with Softmax", "tiles", 1},
        {"attention_pv_matrix_overlap_hits", "Overlapped PV matrices ready before Softmax completion", "tiles", 1},
        {"attention_pv_matrix_overlap_waits", "Overlapped PV matrices pending at Softmax completion", "tiles", 1},
        {"attention_qk_matrix_broadcasts", "QK matrix group broadcasts", "broadcasts", 1},
        {"attention_pv_matrix_broadcasts", "PV matrix group broadcasts", "broadcasts", 1},
        {"attention_qk_array_ops", "QK array operations", "operations", 1},
        {"attention_qk_early_compute_arrays", "QK array operations started during input programming", "operations", 1},
        {"attention_qk_input_pipeline_rows_fetched", "QK K rows fetched through the bounded input pipeline", "rows", 1},
        {"attention_qk_input_pipeline_rows_programmed", "QK K rows programmed through the bounded input pipeline", "rows", 1},
        {"attention_qk_input_pipeline_overlap_ticks", "Ticks with QK Local GM read and Array input programming both active", "ticks", 1},
        {"attention_qk_input_pipeline_slot_full_stalls", "QK input producer attempts blocked by two occupied row slots", "stalls", 1},
        {"attention_qk_input_pipeline_max_depth", "Maximum occupied QK K-row staging slots per panel", "slots", 1},
        {"attention_qk_input_pipeline_tag_mismatches", "QK input pipeline ownership or callback tag mismatches", "mismatches", 1},
        {"attention_qk_readout_ahead_depth", "QK outputs issued ahead of ordered Local GM retirement", "outputs", 1},
        {"attention_cross_tile_operand_candidates", "Grouped follower tiles eligible for cross-tile operand preload", "tiles", 1},
        {"attention_cross_tile_operand_launches", "Cross-tile follower query reads launched", "tiles", 1},
        {"attention_cross_tile_operand_matrix_programs", "Ahead QK matrices programmed into inactive operand banks", "matrices", 1},
        {"attention_cross_tile_operand_input_rows", "Ahead panel-zero K rows programmed into inactive operand banks", "rows", 1},
        {"attention_cross_tile_operand_ready_hits", "Ahead operand contexts ready before follower commit", "tiles", 1},
        {"attention_cross_tile_operand_waits", "Follower commits that waited for an ahead operand context", "tiles", 1},
        {"attention_cross_tile_operand_wait_ticks", "Ticks follower commits waited for ahead operands", "ticks", 1},
        {"attention_cross_tile_operand_promotions", "Ahead operand contexts promoted to active", "tiles", 1},
        {"attention_cross_tile_operand_tag_mismatches", "Ahead operand ownership or callback tag mismatches", "mismatches", 1},
        {"attention_cluster_ahead_contexts_launched", "Cluster follower contexts launched into the ahead pipeline", "contexts", 1},
        {"attention_cluster_ahead_contexts_completed", "Cluster follower contexts completing QK and Softmax", "contexts", 1},
        {"attention_cluster_ahead_contexts_promoted", "Ready cluster follower contexts promoted into PV", "contexts", 1},
        {"attention_cluster_promotion_waits", "Follower transitions waiting for an ahead context to become ready", "waits", 1},
        {"attention_cluster_initial_enqueue_retries", "Transient initial command enqueue rejections retried by the cluster scheduler", "retries", 1},
        {"attention_cluster_qk_tile_starts", "Logical QK tile starts across current and ahead contexts", "tiles", 1},
        {"attention_cluster_qk_boundary_ii_cycles", "QK tile-start intervals crossing a key or group boundary", "cycles", 1},
        {"attention_cluster_qk_steady_ii_over_target", "Steady QK tile intervals above the 625-cycle target", "intervals", 1},
        {"attention_cluster_qk_tile_ii_cycles", "Cycles between consecutive logical QK tile starts", "cycles", 1},
        {"attention_cluster_qk_sfu_overlap_cycles", "Cycles with QK arrays and SFU active concurrently", "cycles", 1},
        {"attention_cluster_sfu_pv_overlap_cycles", "Cycles with SFU and PV arrays active concurrently", "cycles", 1},
        {"attention_cluster_qk_pv_overlap_cycles", "Cycles with QK and PV arrays active concurrently", "cycles", 1},
        {"attention_cluster_three_stage_overlap_cycles", "Cycles with QK arrays, SFU, and PV arrays all active", "cycles", 1},
        {"attention_pv_array_ops", "PV array operations", "operations", 1},
        {"attention_generic_gemm_qk_ops", "Attention QK operations launched through the shared GEMM engine", "operations", 1},
        {"attention_generic_gemm_pv_ops", "Attention PV operations launched through the shared GEMM engine", "operations", 1},
        {"attention_pv_active_k_launches", "PV array launches using active key columns", "launches", 1},
        {"attention_pv_active_k_columns", "Aggregate active key columns across PV launches", "columns", 1},
        {"attention_pv_active_k_matrix_elements", "Aggregate compact PV matrix elements programmed into array banks", "elements", 1},
        {"attention_pv_v_tile_buffer_hits", "PV V tile buffer hits", "hits", 1},
        {"attention_pv_v_tile_buffer_misses", "PV V tile buffer misses", "misses", 1},
        {"attention_pv_v_tile_buffer_bytes_read", "Bytes read from Local GM to serve PV V tile accesses", "bytes", 1},
        {"attention_pv_v_tile_buffer_bytes_reused", "PV V tile bytes served by buffer hits", "bytes", 1},
        {"attention_pv_v_tile_buffer_wait_ticks", "Cycles spent waiting for PV V tile buffer hits", "ticks", 1},
        {"attention_pv_v_tile_buffer_capacity_rejections", "PV V tile accesses rejected because the tile exceeds buffer capacity", "accesses", 1},
        {"attention_pv_v_tile_buffer_group_hits", "Follower-query panel-zero accesses served by retained V staging", "hits", 1},
        {"attention_pv_input_residency_hits", "PV dimension panels reusing resident array inputs", "panels", 1},
        {"attention_pv_input_residency_rows_reused", "PV input rows served by resident array input SRAM", "rows", 1},
        {"attention_pv_input_residency_invalidations", "PV input residency tags invalidated at key-tile boundaries", "invalidations", 1},
        {"attention_o_accumulator_stores", "Intermediate FP32 Attention O rows stored in WCP C-buffer", "rows", 1},
        {"attention_o_accumulator_restores", "Intermediate FP32 Attention O rows restored from WCP C-buffer", "rows", 1},
        {"attention_o_accumulator_bytes", "FP32 Attention O bytes transferred through WCP C-buffer", "bytes", 1},
        {"attention_sp_hbm_bytes", "Score/probability HBM bytes", "bytes", 1},
        {"attention_cluster_config_fingerprint", "Stable Attention cluster configuration fingerprint", "hash", 1},
        {"attention_cluster_worker_jobs", "Worker jobs routed through the Attention cluster", "jobs", 1},
        {"attention_cluster_contexts_issued", "Cluster contexts issued", "contexts", 1},
        {"attention_cluster_contexts_completed", "Cluster contexts completed", "contexts", 1},
        {"attention_cluster_contexts_cancelled", "Cluster contexts cancelled", "contexts", 1},
        {"attention_cluster_bank_refs_cancelled", "Cluster operand-bank references cancelled", "references", 1},
        {"attention_cluster_memory_requests_cancelled", "Cluster DMA and Local-GM requests cancelled", "requests", 1},
        {"attention_cluster_context_high_water", "Maximum simultaneous live cluster contexts", "contexts", 1},
        {"attention_cluster_stale_callbacks", "Cluster callbacks rejected by generation or tag", "callbacks", 1},
        {"attention_cluster_illegal_transitions", "Illegal cluster ownership or lifecycle transitions", "transitions", 1},
        {"attention_cluster_score_slot_reservations", "Complete score tile slots reserved", "slots", 1},
        {"attention_cluster_score_slot_releases", "Complete score tile slots released", "slots", 1},
        {"attention_cluster_score_slot_full_stalls", "Score producers blocked by full slots", "stalls", 1},
        {"attention_cluster_score_slot_high_water", "Maximum occupied score slots", "slots", 1},
        {"attention_cluster_o_context_reservations", "Resident O contexts reserved", "contexts", 1},
        {"attention_cluster_o_context_releases", "Resident O contexts released", "contexts", 1},
        {"attention_cluster_o_context_cancelled", "Resident O contexts cancelled", "contexts", 1},
        {"attention_cluster_o_context_high_water", "Maximum resident O contexts", "contexts", 1},
        {"attention_cluster_o_scale_segments", "Resident O alpha-scale segment operations", "segments", 1},
        {"attention_cluster_o_accumulate_segments", "Resident O accumulation segment operations", "segments", 1},
        {"attention_cluster_o_fused_rows", "PV output rows submitted through the fused O path", "rows", 1},
        {"attention_cluster_o_fused_bytes", "PV output bytes consumed by the fused O path", "bytes", 1},
        {"attention_cluster_o_drain_requests", "Resident O final drain requests", "requests", 1},
        {"attention_cluster_o_drain_bytes", "Resident O final drain bytes", "bytes", 1},
        {"attention_cluster_o_read_wait_cycles", "Resident O SRAM read-port wait", "cycles", 1},
        {"attention_cluster_o_write_wait_cycles", "Resident O SRAM write-port wait", "cycles", 1},
        {"attention_cluster_o_alu_wait_cycles", "Resident O ALU issue wait", "cycles", 1},
        {"attention_cluster_o_bank_conflict_cycles", "Resident O row-bank conflict wait", "cycles", 1},
        {"attention_cluster_o_drain_wait_cycles", "Resident O final-drain wait", "cycles", 1},
        {"attention_cluster_o_read_busy_union_cycles", "Union of resident O read-port service intervals", "cycles", 1},
        {"attention_cluster_o_read_busy_span_cycles", "Span of resident O read-port service intervals", "cycles", 1},
        {"attention_cluster_o_read_idle_gap_cycles", "Idle gaps inside resident O read-port service span", "cycles", 1},
        {"attention_cluster_o_read_max_concurrency", "Maximum resident O read-port service concurrency", "operations", 1},
        {"attention_cluster_o_write_busy_union_cycles", "Union of resident O write-port service intervals", "cycles", 1},
        {"attention_cluster_o_write_busy_span_cycles", "Span of resident O write-port service intervals", "cycles", 1},
        {"attention_cluster_o_write_idle_gap_cycles", "Idle gaps inside resident O write-port service span", "cycles", 1},
        {"attention_cluster_o_write_max_concurrency", "Maximum resident O write-port service concurrency", "operations", 1},
        {"attention_cluster_o_alu_busy_union_cycles", "Union of resident O ALU issue intervals", "cycles", 1},
        {"attention_cluster_o_alu_busy_span_cycles", "Span of resident O ALU issue intervals", "cycles", 1},
        {"attention_cluster_o_alu_idle_gap_cycles", "Idle gaps inside resident O ALU issue span", "cycles", 1},
        {"attention_cluster_o_alu_max_concurrency", "Maximum resident O ALU issue concurrency", "operations", 1},
        {"attention_cluster_qk_array_busy_union_ticks", "Union of cluster QK array busy intervals", "ticks", 1},
        {"attention_cluster_qk_array_busy_span_ticks", "Span of cluster QK array busy intervals", "ticks", 1},
        {"attention_cluster_qk_array_idle_gap_ticks", "Idle gaps inside the cluster QK array busy span", "ticks", 1},
        {"attention_cluster_qk_array_max_concurrency", "Maximum concurrent cluster QK array operations", "arrays", 1},
        {"attention_cluster_pv_array_busy_union_ticks", "Union of cluster PV array busy intervals", "ticks", 1},
        {"attention_cluster_pv_array_busy_span_ticks", "Span of cluster PV array busy intervals", "ticks", 1},
        {"attention_cluster_pv_array_idle_gap_ticks", "Idle gaps inside the cluster PV array busy span", "ticks", 1},
        {"attention_cluster_pv_array_max_concurrency", "Maximum concurrent cluster PV array operations", "arrays", 1},
        {"attention_cluster_qk_k_tile_broadcasts", "K-tile broadcasts to four QK arrays", "broadcasts", 1},
        {"attention_cluster_qk_k_tile_bytes", "K-tile ingress bytes", "bytes", 1},
        {"attention_cluster_qk_q_pair_multicasts", "Q vector multicasts to QK array pairs", "multicasts", 1},
        {"attention_cluster_qk_q_pair_bytes", "Q pair multicast ingress bytes", "bytes", 1},
        {"attention_cluster_qk_score_beats", "Direct query-major QK score beats", "beats", 1},
        {"attention_cluster_qk_score_bytes", "Direct query-major QK score bytes", "bytes", 1})

    RoCCAnalogInt(ComponentId_t id, Params &params)
        : RoCCAnalog<int64_t>(id, params) {}
};

} // namespace Golem
} // namespace SST

#endif
